# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

pool:
  vmImage: 'macOS-10.13'

steps:
- checkout: self 
  persistCredentials: true
    
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- task: DownloadSecureFile@1
  inputs:
    secureFile: 'StanfordDaily_dist.p12'

- task: DownloadSecureFile@1
  inputs:
    secureFile: 'StanfordDaily.mobileprovision'

- script: |
    npm install
    npm install -g turtle-cli gulp-cli
  displayName: 'npm install'

- script: |
    turtle build:ios --team-id ${TEAM_ID} --dist-p12-path ${TEMP_DIRECTORY}/StanfordDaily_dist.p12 --provisioning-profile-path ${TEMP_DIRECTORY}/StanfordDaily.mobileprovision
  displayName: 'build ios'
  env:
    EXPO_USERNAME: $(EXPO_USERNAME)
    EXPO_PASSWORD: $(EXPO_PASSWORD)
    TEAM_ID: $(TEAM_ID)
    EXPO_IOS_DIST_P12_PASSWORD: $(EXPO_IOS_DIST_P12_PASSWORD)
    TEMP_DIRECTORY: $(Agent.TempDirectory)
